[package]
name = "example-host"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
clap = { version = "4.3.19", features = ["derive"] }
wasmtime = "20.0.2"
wasmtime-wasi = { version = "20.0.2" }
anyhow = "1.0.72"
